spring:
  application:
    name: expertise

  config:
    import: optional:configserver:http://root:s3cr3t@localhost:8888

  cloud:
    config:
      uri: http://localhost:8888/
      name: common,expertise

  profiles:
    active: dev,deploy-intermediation

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

file:
  upload:
#    directory: ${user.home}/uploads/competences
    directory: D:\Binaries\uploads\competences

# Configuration Zeebe pour orchestration BPMN
camunda:
  client:
    mode: simple
    zeebe:
      base-url: http://localhost:26500
