spring:
  application:
    name: Auth

  config:
    import: optional:configserver:http://root:s3cr3t@localhost:8888

  cloud:
    config:
      uri: http://localhost:8888/
      name: common,security-common,db-common,auth

# Configuration Zeebe pour envoyer des messages BPMN
camunda:
  client:
    zeebe:
      base-url: http://localhost:26500
